# Generated by Django 4.0.4 on 2022-05-17 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_measurement_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='created_date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
